# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Far-Fetched Advisory and Consulting
email: info@farfetched.ltd
description: >-
  Strategic technology leader with over 20 years’ experience in software engineering, platform architecture, and organizational design. Far-Fetched Advisory and Consulting partners with digital businesses, especially in iGaming and other regulated or high-growth sectors—to scale platforms, optimize delivery, and raise engineering standards. We specialize in high-performance systems, team structuring, and product–tech alignment for ambitious companies seeking sustainable growth.

baseurl: "" # Leave empty when using a custom domain on GitHub Pages
url: "https://www.farfetched.ltd"
twitter_username: nrdsrfr
linkedin_username: jessecary
github_username: nrdsrfr

# Output built site to /docs for GitHub Pages
source: docs
destination: docs/_site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - "**/README.md"
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/